# Generated by Django 3.2.14 on 2022-09-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargen', '0002_add_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('Character', 'Character'), ('Place', 'Place'), ('Object', 'Object'), ('Other', 'Other')], default='Character', max_length=50),
        ),
    ]
