# Generated by Django 3.2.14 on 2022-09-21 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chargen', '0004_rename_char_to_story'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='character_image',
            new_name='story_image',
        ),
        migrations.RemoveField(
            model_name='story',
            name='post_category',
        ),
        migrations.AddField(
            model_name='story',
            name='story_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='story_category', to='chargen.category'),
        ),
        migrations.AlterField(
            model_name='story',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
