# Generated by Django 3.2.14 on 2022-09-21 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chargen', '0006_alter_story_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
