# Generated by Django 3.2.14 on 2022-09-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargen', '0008_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='summary',
            field=models.CharField(max_length=100),
        ),
    ]
